# config/lab6_landmarks.yaml

landmarks:
  - color: "red"
    x: 8.5
    y: -5.0
    z: 0.25
    radius: 0.1
    height: 0.5
    topic: "/vision_red/corners"

  - color: "green"
    x: 8.5
    y: 5.0
    z: 0.25
    radius: 0.1
    height: 0.5
    topic: "/vision_green/corners"

  - color: "yellow"
    x: -11.5
    y: 5.0
    z: 0.25
    radius: 0.1
    height: 0.5
    topic: "/vision_yellow/corners"

  - color: "magenta"
    x: -11.5
    y: -5.0
    z: 0.25
    radius: 0.1
    height: 0.5
    topic: "/vision_magenta/corners"

  - color: "cyan"
    x: 0.0
    y: 0.0
    z: 0.25
    radius: 0.1
    height: 0.5
    topic: "/vision_cyan/corners"